language: node_js
node_js:
  - "6.1.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mongodb

#blacklist
branches:
  except:
    - deploy_dev
    - deploy_qa
    - deploy_staging

git:
  submodules: false  

notifications:
  irc:
    channels:
      - "irc.freenode.org#periodicjs"
    template:
      - "Build by %{author} :"
      - "Git Info: %{branch} - %{commit} with the message %{commit_message}"
      - "Travis states: %{message}"
      - "Build Details: %{build_url}"
      - "Change View: %{compare_url}"
      - "result = %{result}"
      - "elapsed time... %{duration}"
    use_notice: true
    skip_join: false

before_install:
 - npm config set //registry.npmjs.org/:_authToken=\${NPM_TOKEN}
 - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_script:
  - npm config set //registry.npmjs.org/:_authToken=540c69b8-20f8-4fdc-947d-e26d75f4492c && npm install -g grunt-cli istanbul

script: 
  - npm config set //registry.npmjs.org/:_authToken=540c69b8-20f8-4fdc-947d-e26d75f4492c && npm set progress=false && npm install && grunt test && grunt coveralls

# whitelist
# branches:
#  only:
#    - master
#    - stable